#Adicionar endereço
POST http://127.0.0.1:8000/ludomagalu@gmail.com/addresses HTTP/1.1
content-type: application/json

    {
        "name": "minha casa"
        "street": "Rua da Colina"
        "house_number": 3214
        "zipcode": "19453-019",
        "city": "Franca",
        "state": "SP",
    
    }

#######################################
# Buscar endereços
GET http://127.0.0.1:8000/ludomagalu@gmail.com/addresses HTTP/1.1
content-type: application/json

#######################################
# Deletar endereço
DELETE  http://127.0.0.1:8000/ludomagalu@gmail.com/addresses/01 HTTP/1.1
content-type: application/json