# Adicionar endereço
POST http://127.0.0.1:8000/001/addresses HTTP/1.1
content-type: application/json

    {
        "cep": "19453-019",
        "cidade": "Franca",
        "estado": "SP",
        "logradouro": "Rua da Colina",
        "numero": 2012
    }

#######################################
# Buscar endereços
GET http://127.0.0.1:8000/001/addresses HTTP/1.1
content-type: application/json

#######################################
# Deletar endereço
DELETE  http://127.0.0.1:8000/001/addresses/01 HTTP/1.1
content-type: application/json