# Cadastrar produto
POST http://127.0.0.1:8000/api/product/ HTTP/1.1
content-type: application/json

{
    "id": "3",
    "name": "Jogo de Cama Casal Queen - Kit 6 Peças",
    "description": "O jogo de cama M. F. Enxovais tem o estilo moderno cosmopolita, trazendo em sua composição tons de salmão, bege e azul, facilitando combinações com diversas cores, deixando o quarto mais alegre e confortável com alta qualidade",
    "category": "Cama",
    "subcategory": "Jogo de Cama",
    "brand": "M. F. Enxovais",
    "color": "Salmão, bege e azul",
    "fabric": "100% poliéster",
    "dimensions": "1 Edre m \n- 2 Pse \n- 1 Len",
    "items_quantity": 6,
    "price": 295.90
}

####
# Atualizar dados do produto
PUT http://127.0.0.1:8000/api/product/3 HTTP/1.1
content-type: application/json

{
    "name": "toalha de banho megabanhão",
    "category": "Toalha",
    "color": "Rosa",
    "fabric": "100% algodão",
    "price": 525.99
}

####
# Consultar produto por código
GET http://127.0.0.1:8000/api/product/search_id/3 HTTP/1.1
content-type: application/json

####
# Consultar produto por nome
GET http://127.0.0.1:8000/api/product/search_name/toalha HTTP/1.1
content-type: application/json

####
# Deletar um produto por código
DELETE http://127.0.0.1:8000/api/product/10001 HTTP/1.1
content-type: application/json


