POST http://127.0.0.1:8000/magaluJA/transaction-history/teste2@gmail.com HTTP/1.1
content-type: application/json

{
    "id": "00004",
    "products": [],
    "price": 10.5,
    "number_of_items": 5,
    "delivery_address": {},
    "payment_method": "credit"
}

#####
GET http://127.0.0.1:8000/magaluJA/transaction-history/poliana@gmail.com/00001 HTTP/1.1
####
GET http://127.0.0.1:8000/magaluJA/transaction-history/poliana@gmail.com/ HTTP/1.1