POST http://127.0.0.1:8000/magaluJA/shopping-cart/joana@gmail.com/ HTTP/1.1
content-type: application/json

{
    "product_id": "00003",
    "quantity": 4
}
####
GET http://127.0.0.1:8000/magaluJA/shopping-cart/taila004@gmail.com/products/00001 HTTP/1.1
####
GET http://127.0.0.1:8000/magaluJA/shopping-cart/mari001@gmail.com/products/ HTTP/1.1
####
GET http://127.0.0.1:8000/magaluJA/shopping-cart/joana@gmail.com/ HTTP/1.1
####

DELETE http://127.0.0.1:8000/magaluJA/shopping-cart/joana@gmail.com/00003/ HTTP/1.1
####
DELETE http://127.0.0.1:8000/magaluJA/shopping-cart/joana@gmail.com/ HTTP/1.1
####
PUT http://127.0.0.1:8000/magaluJA/shopping-cart/joana@gmail.com/ HTTP/1.1
content-type: application/json

{
    "product_id": "00003",
    "quantity": -1
}
####