POST http://127.0.0.1:8000/magaluJA/users/ HTTP/1.1
content-type: application/json

{
    "email": "mari1@gmail.com",
    "name": "mari",
    "password": "mari",
    "addresses": [],
    "shopping_cart":{
        "user_email": "mari1@gmail.com",
        "products": [],
        "price_credit": 0.0,
        "price_debit": 0.0,
        "number_of_items": 0,
        "delivery_address_id": ""
        },
    "transaction_history":{
        "user_email": "mari1@gmail.com",
        "transaction_history": []
    }
}
####
GET http://127.0.0.1:8000/magaluJA/users/mari1@gmail.com HTTP/1.1
####
DELETE http://127.0.0.1:8000/magaluJA/users/mari@gmail.com HTTP/1.1
####
PUT http://127.0.0.1:8000/magaluJA/users/mari@gmail.com HTTP/1.1
content-type: application/json

{
    "name": "aaaaaaaa",
    "password": "aaaaaaaa"
}

####