# Criar usuário
POST http://127.0.0.1:8000/magaluJA/users/ HTTP/1.1
content-type: application/json

{
    "id": 223,
    "name": "Maria da Silva",
    "email": "jjj@gmail.com",
    "password": "maria1234",
    "addresses": []
}

### Consultar usuário por email
GET http://127.0.0.1:8000/api/user/mariadasilva@gmail.com HTTP/1.1
content-type: application/json


####S Consultar usuário por nome
GET http://127.0.0.1:8000/api/user/Maria+da+Silva HTTP/1.1
content-type: application/json


# Deletar usuário por email
DELETE http://127.0.0.1:8000/api/user/mariadasilva@gmail.com HTTP/1.1
content-type: application/json


# Atualizar usuário por email
PUT http://127.0.0.1:8000/api/user/mariadasilva@gmail.com HTTP/1.1
content-type: application/json

{
    "name": "aaaaaaaa",
    "password": "aaaaaaaa"
}

####